In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

In [2]:
# 분류를 위한 시퀀스 생성 함수
def split_sequence(sequence, n_steps):
    X, y = [], []
    for i in range(len(sequence)):
        end_ix = i + n_steps
        if end_ix > len(sequence) - 1:
            break
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y // 10)  # 클래스 레이블 생성
    return np.array(X), np.array(y)

In [8]:
# 사용 예시
sequence = [10, 20, 30, 40, 50, 60, 70, 80, 90]
n_steps = 3
X, y = split_sequence(sequence, n_steps)
print("X:\n", X)
print("y:\n", y)

X:
 [[10 20 30]
 [20 30 40]
 [30 40 50]
 [40 50 60]
 [50 60 70]
 [60 70 80]]
y:
 [4 5 6 7 8 9]


In [13]:
# LSTM 모델 정의
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(X.shape[1], 1)))
model.add(Dropout(0.2))
model.add(Dense(10, activation='softmax'))  # 분류 문제를 위해 소프트맥스 사용

In [14]:
# 모델 컴파일
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [15]:
# 데이터 형태 조정
X = X.reshape((X.shape[0], X.shape[1], 1))

In [16]:
# 모델 학습
model.fit(X, y, epochs=200, verbose=0)

In [17]:
# 예측
y_pred = model.predict(X)
print("Predictions:\n", y_pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step
Predictions:
 [[1.63724589e-10 1.24661637e-09 5.86521744e-17 5.15230580e-10
  9.76262629e-01 2.37229429e-02 1.43827174e-05 2.91326512e-11
  2.95829137e-14 1.42352030e-09]
 [3.72006383e-07 2.55479051e-07 2.05135578e-13 2.61151996e-07
  5.64711690e-01 4.30918187e-01 4.36464231e-03 3.37582435e-07
  4.68948491e-10 4.27118175e-06]
 [5.41623402e-03 1.73511682e-03 2.85364331e-05 3.58742801e-03
  8.10246989e-02 1.69969723e-01 6.05666935e-01 1.07444234e-01
  6.27160119e-03 1.88555047e-02]
 [1.76260471e-02 7.19095347e-03 1.48901495e-03 2.58164201e-02
  2.84221489e-02 6.48728311e-02 3.70969087e-01 2.75771528e-01
  1.09549776e-01 9.82922539e-02]
 [2.01805253e-02 9.82237887e-03 4.47973609e-03 5.48666231e-02
  1.35134747e-02 5.21692149e-02 2.03848600e-01 1.55067220e-01
  2.48043999e-01 2.38008201e-01]
 [1.50299277e-02 8.12582113e-03 5.82167879e-03 7.03798607e-02
  5.47121232e-03 3.96738201e-02 1.00991383e-01 6.53839186e-02
  3.09939891e-01 3.79182458e-01]]
